/*
 * Minimal client for a model-specific libai_model.so generated by:
 *
 *   model_deploy.py static-library --shared --model MODEL.tflite ...
 *
 * The model and TensorFlow Lite CPU runtime live in libai_model.so.  This
 * program is deliberately an ordinary application: replace fill_input() with
 * the caller's feature-extraction code and link this source with -lai_model.
 */
#include <stdio.h>

#include "ai_model.h"

#define FEATURE_COUNT 240
#define CLASS_COUNT 5

static void fill_input(float input[FEATURE_COUNT])
{
    /* Test-only input.  Replace with the 240 float32 values produced by the
     * application feature extractor.  Their order and normalization must
     * match the model used to produce libai_model.so. */
    for (int i = 0; i < FEATURE_COUNT; ++i) {
        input[i] = ((float)(i % 40) - 20.0f) / 10.0f;
    }
}

int main(void)
{
    float input[FEATURE_COUNT];
    float scores[CLASS_COUNT];
    size_t score_count = 0;
    int label = -1;
    double latency_ms = 0.0;

    fill_input(input);

    if (ai_model_init() != 0) {
        fprintf(stderr, "ai_model_init failed\n");
        return 1;
    }
    if (ai_model_predict(input, FEATURE_COUNT, scores, CLASS_COUNT,
                         &score_count, &label, &latency_ms) != 0) {
        fprintf(stderr, "ai_model_predict failed\n");
        ai_model_deinit();
        return 1;
    }

    printf("score_count=%zu\n", score_count);
    printf("scores=");
    for (size_t i = 0; i < score_count; ++i) {
        printf("%s%.9g", i == 0 ? "" : ",", scores[i]);
    }
    printf("\nlabel=%d\nlatency_ms=%.3f\n", label, latency_ms);

    ai_model_deinit();
    return 0;
}
